### ISSUE TITLE
Check literature for priors

### ISSUE THREAD

**Issue by mdscheuerell** [mdscheuerell/mar_sims#4]
We should consider more informative priors for the elements in __B__ and the observation variance. For example, if working with plankton like _Daphnia_, information could be taken from Ives et al (2003) or Hampton et al (2006).

**Comment by sl-katz63** [comment]
What does “assigned” mean in this context?

Do I have a specific job or is that jargon for we sent him a link?

Thanks
SLK


Sent from my Abacus, so please excuse the small number of significant figures.

On Aug 15, 2019, at 3:37 PM, Mark Scheuerell <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #4<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mdscheuerell_mar-5Fsims_issues_4&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=A-lXv-nHAz9Gby1H_SQFwfRFAYkK9DJj4otOouLz7ak&m=WmUTDsAADDfEUcj0LDczwzXk9lLVIribQPm6k9zAC90&s=PyCJuNcXTI1mKnNCNXSmLDw_vA-OtVa-M6Hxd9B3lbE&e=> to @sl-katz63<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sl-2Dkatz63&d=DwMCaQ&c=C3yme8gMkxg_ihJNXS06ZyWk4EJm8LdrrvxQb-Je7sw&r=A-lXv-nHAz9Gby1H_SQFwfRFAYkK9DJj4otOouLz7ak&m=WmUTDsAADDfEUcj0LDczwzXk9lLVIribQPm6k9zAC90&s=579w12KXOMUMKyk_0vEc_rGnm_x1nPTuvHRyHky4dPI&e=>.

**Comment by mdscheuerell** [comment]
@sl-katz63: that just means you (us) should be thinking/working on it.

**Comment by ericward-noaa** [comment]
Most papers written before ~ 2005 used Gibbs sampling, and adopted conjugate priors (normal on coefficients, inverse gamma on variances). I still see a lot of papers using those priors. 

I guess I'd propose looking at 3 priors on variances:
- inverse gamma prior (examples below)
- vauge normal priors used by Auger-Methe and others
- Student-t priors, proposed by Aki https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations

1. Carlin et al. 1992 "A Monte Carlo approach to nonnormal and nonlinear
 state space modeling" uses inverse gamma priors on variances and normal for regression coefficients because the estimation approach used was Gibbs sampling

2. Carter and Kohn 1994 "On Gibbs Sampling for State Space Models" used improper priors, proportional to half-normal

3. Wikle et al. 1998 "Hierarchical Bayesian space-time models", conjugate inverse gamma priors

4. Nakajima et al. 2009 "Bayesian Analysis of Time-Varying Parameter Vector Autoregressive Model for the Japanese Economy and Monetary Policy", inverse gamma priors

5. Chan and Eisenstat 2018 "Bayesian model comparison for time‐varying parameter VARs with stochastic volatility", conjugate inverse gamma priors
